# Generated by Django 2.2.10 on 2020-03-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200229_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='sticky',
            field=models.BooleanField(default=False),
        ),
    ]
