# Generated by Django 2.2.10 on 2020-03-26 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_sticky'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['sticky', 'last_updated_time', '-created_time']},
        ),
    ]
