# Generated by Django 2.2.10 on 2020-03-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200326_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='sticky',
            field=models.IntegerField(default=0),
        ),
    ]
