# Generated by Django 2.2.10 on 2020-03-26 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200326_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-sticky', '-last_updated_time', '-created_time']},
        ),
    ]
